#!/bin/sh

transBLUE=$(printf '\033[38;2;91;206;250m')
transPINK=$(printf '\033[38;2;245;169;184m')
transWHITE=$(printf '\033[38;2;255;255;255m')

BLACK=$(printf '\033[30m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
MAGENTA=$(printf '\033[35m')
CYAN=$(printf '\033[36m')
WHITE=$(printf '\033[37m')

BRIGHT_BLACK=$(printf '\033[90m')
BRIGHT_RED=$(printf '\033[91m')
BRIGHT_GREEN=$(printf '\033[92m')
BRIGHT_YELLOW=$(printf '\033[93m')
BRIGHT_BLUE=$(printf '\033[94m')
BRIGHT_MAGENTA=$(printf '\033[95m')
BRIGHT_CYAN=$(printf '\033[96m')
BRIGHT_WHITE=$(printf '\033[97m')

BOLD=$(printf '\033[1m')
UNDERLINE=$(printf '\033[4m')

RESET=$(printf '\033[0m')

if [ "$1" = "--verbose" ]; then
  err() {
    printf '%s\n' "$RED$*$RESET" >&2
  }

  log(){
    printf '%s\n' "$CYAN$*$RESET" >&2
  }

  log "Logging is enabled!"
else
  err() {
    :
  }

  log(){
    :
  }
fi

color() {
  printf '%s%s%s\n' "$1" "$2" "$RESET"
}

info() {
  printf '%-10s : %s\n' "$1" "$GREEN$2$RESET"
}

BOX="█████████████████████████████"

logo=$(
  color "$transBLUE" "$BOX"
  color "$transBLUE" "$BOX"
  color "$transPINK" "$BOX"
  color "$transPINK" "$BOX"
  color "$transWHITE" "$BOX"
  color "$transWHITE" "$BOX"
  color "$transPINK" "$BOX"
  color "$transPINK" "$BOX"
  color "$transBLUE" "$BOX"
  color "$transBLUE" "$BOX"
)



if command >/dev/null 2>&1; then
  hascmd() {
    command -v "$1" >/dev/null 2>&1
  }
else
  if type >/dev/null 2>&1; then
    err "Command '${UNDERLINE}command$RESET${RED}' not found! Falling back to 'type'."
    hascmd() {
      type "$1" >/dev/null 2>&1
    }
  else
    hascmd(){
      old_ifs=$IFS
      IFS=:
      for dir in $PATH; do
        [ -x "${dir:-.}/$1" ] && {
          IFS=$old_ifs
          return 0
        }
      done
      IFS=$old_ifs
      return 1
    }
  fi
fi

# Use this when the entire shit is done
print_fetch() {
  log "printing..."
  info=$1

  exec 3<<EOF
$info
EOF

  while :; do
    logo_line=
    info_line=

    if IFS= read -r logo_line <&0; then
      logo_done=0
    else
      logo_done=1
    fi

    if IFS= read -r info_line <&3; then
      info_done=0
    else
      info_done=1
    fi

    [ "$logo_done" = 1 ] && [ "$info_done" = 1 ] && break

    printf '%-29s %s\n' "$logo_line" "$info_line"

    unset logo_done info_done
  done <<EOF
$logo
EOF

  exec 3<&-
}

if hascmd uname; then
  OS=$(uname -s)
  log "Found OS : $OS"
else
  OS=Linux
  err "Command '${UNDERLINE}uname$RESET${RED}' not found! Defaulting to Linux."
fi

Init() {
  :
}

Memory() {
  :
}

CPU() {
  :
}

Uptime() {
  :
}

Music() {
  :
}

LoadAVG() {
  :
}

OS() {
  :
}

if [ "$OS" = "Darwin" ]; then
  if ! hascmd sysctl; then
    err "Command '${UNDERLINE}sysctl$RESET${RED}' not found! Aborting fetch."
    exit 1
  fi
  log "Checked that \`sysctl\` exists."
fi

case "$OS" in
Darwin)
  err "${UNDERLINE}DARWIN$RESET${RED} DETECTED......."
  Hostname() {
    printf '%s\n' "$GREEN$USER$RESET@$BLUE$(sysctl -n kern.hostname)$RESET"
  }

  Init() {
    info "Init" "${YELLOW}launchd"

  }

  Desktop() {
    info "Desktop" "${YELLOW}Springboard"
  }

  OS() {
    case "$(sysctl -n hw.product)" in
    iPhone*)
      DarwinOS=iOS
      ;;
    iPad*)
      DarwinOS=iPadOS
      ;;
    *)
      DarwinOS=macOS
      ;;
    esac
    log "DarwinOS : $DarwinOS"
    DarwinOSVer="$(sysctl -n kern.osproductversion)"
    log "Version : $DarwinOSVer"
    info "OS" "$DarwinOS $DarwinOSVer"
  }

  Memory() {
    MemBytes="$(sysctl -n hw.memsize)"
    MemMiB=$((MemBytes / 1024 / 1024))
    swap=$(sysctl -n vm.swapusage)
    log "Memory : $MemMiB"
    log "Swap : $swap"
    info "Memory" "${MemMiB}MiB (Swap : $swap)"
  }

  CPU() {
    CPU="$(sysctl -n machdep.cpu.brand_string)"
    log "CPU : $CPU"
    info "CPU" "$CPU"
  }

  if hascmd awk; then
    log "awk exists!"

    Uptime() {
      Boot="$(sysctl -n kern.boottime | awk -F'[ =,}]+' '{print $3}')"
      Now="$(date +%s)"
      Uptime=$((Now - Boot))

      log "Uptime : $Uptime"

      info "Uptime" \
        "$((Uptime / 86400)) days, $(printf '%02d:%02d:%02d' \
          "$((Uptime / 3600 % 24))" \
          "$((Uptime / 60 % 60))" \
          "$((Uptime % 60))")"
    }

    LoadAVG() {
      Load="$(sysctl -n vm.loadavg | awk '{print $2, $3, $4}')"
      log "Load avg : $Load"
      info "Load AVG" "$Load"
    }

  else
    err "What kind of apple produc is this that have ${UNDERLINE}no awk$RESET${RED}?"
  fi

  err "Darwin ${UNDERLINE}doesn't expose music metadata$RESET ${BLACK}:${RED}("

  ;;

Linux | MINGW* | MSYS* | CYGWIN*)
  if ! [ "$OS" = "Linux" ]; then
    err "${UNDERLINE}Windows$RESET${RED} DETECTED.."
  fi

  Hostname() {
    if [ "x$USER" = "x" ]; then
      err "${UNDERLINE}\$USER$RESET${RED} might not exist in this environment....Trying \$USERNAME"
      if [ "x$USERNAME" = "x" ]; then
        printf '%s' "$BOLD${RED}idk$RESET"
        err "${UNDERLINE}\$USERNAME$RESET${RED} might not exist in this environment......"
      else
        printf '%s' "$GREEN$USERNAME$RESET"
      fi
    else
      printf '%s' "$GREEN$USER$RESET"
    fi

    if hascmd hostname; then
      printf '%s\n' "${BLUE}@$GREEN$(hostname)$RESET"
    else
      printf '%s\n' "@$BOLD${RED}idk$RESET"
      err "What PC is this with no fucking hostname????"
    fi
  }

  if [ "$OS" = "Linux" ]; then
    if [ -f /etc/os-release ]; then
      OS() {
        . /etc/os-release
        info "OS" "$PRETTY_NAME"
        log "Got \$PRETTY_NAME : $PRETTY_NAME"
      }
    else
      OS() {
        :
      }
      err "${UNDERLINE}/etc/os-release$RESET${RED} not found! Bro have no identity like Mafuyu."
    fi
  else
    OS() {
      info "OS" "${YELLOW}Windows"
    }
  fi

  if hascmd awk; then
    Memory() {
      MemTotal="$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo)"
      MemMiB=$((MemTotal / 1024))
      printf '%-10s : %s ' "Memory" "$GREEN${MemMiB}MiB"
      log "Memory : ${MemMiB}MiB"
      if [ -f /proc/swaps ]; then
        swaps=$(awk 'NR > 1 { printf "%s%s : %sMiB", (NR > 2 ? ", " : "("), $1, $3/1024 } END { print ")" }' /proc/swaps)
        log "Got swap : $swaps"
        printf '%s' "$swaps"
      fi
      printf '%s \n' "$RESET"
    }

    CPU() {
      CPU="$(awk -F: '/^model name/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' /proc/cpuinfo)"

      if [ "x$CPU" = "x" ]; then
        CPU="$(awk -F: '/^system type/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' /proc/cpuinfo)"
      fi

      if [ "x$CPU" = "x" ]; then
        CPU="$BOLD${RED}idk"
        err 'No idea what the hell is the cpu.'
      fi
      
      log "CPU : $CPU"

      info "CPU" "$CPU"
    }

    Uptime() {
      Uptime="$(awk '{printf "%d days, %02d:%02d:%02d\n", $1/86400, $1/3600%24, $1/60%60, $1%60}' /proc/uptime)"
      log "Uptime : $Uptime"
      info "Uptime" "$Uptime"
    }

    if [ "$OS" = "Linux" ]; then
      Init() {
        init="$(awk '/^Name:/ {print $2; exit}' /proc/1/status)"
        if [ "x$init" = "x" ]; then
          init="$BOLD${RED}lol no"
          err "Init so ${BOLD}${UNDERLINE}UNTUFF${RESET}${RED} it hides itself."
        fi
        
        log "Init : $init"

        info "Init" "$init"
      }
    else
      Init() {
        info "Init" "${YELLOW}wininit.exe"
      }
    fi

  else
    err "WHAT THE FUCK THERE'S ${UNDERLINE}NO awk$RESET${RED}???"
  fi

  if [ "$OS" = "Linux" ]; then
    Desktop() {
      if [ "x$DESKTOP_SESSION" != "x" ]; then
        info "Desktop" "$DESKTOP_SESSION"
      else
        err "Are you running in the ${UNDERLINE}tty$RESET${RED}?"
      fi

      log "Desktop : $DESKTOP_SESSION"
    }
  else
    Desktop() {
      info "Desktop" "${YELLOW}explorer.exe"
    }
  fi

  if [ "$OS" = "Linux" ]; then
    if hascmd playerctl; then
      log "playerctl exists!!!!!!! :)"
      Music() {
        title=$(playerctl metadata xesam:title)
        if [ "x$title" != "x" ]; then
          log "THERE IS MUSIC!!!"
          printf '%-10s : %s(%s) : %s\n' \
            "Music" "$GREEN$title" "$(playerctl metadata xesam:artist)" \
            "$(playerctl metadata mpris:length | awk '{ s = int($1 / 1000000); printf "%d:%02d\n", int(s / 60), s % 60 }')$RESET"
        else
          log "Not playing anything :(. Music suggest : Bakenohana(Nightcord at 25.)"
        fi
      }
    else
      err "Command '${UNDERLINE}playerctl$RESET${RED}' not found! No music information :( "
    fi
  else
    err "Cannot get music information from ${UNDERLINE}Windows$RESET${RED} :(."
  fi

  LoadAVG() {
    if [ -f /proc/loadavg ]; then
      IFS= read -r Load </proc/loadavg
      info "Load AVG" "$Load"
      log "Load AVG : $Load"
    else
      err "${UNDERLINE}/proc/loadavg$RESET$RED not found! Maybe there's no load."
    fi
  }
  ;;
*)
  err "idk what OS is $UNDERLINE$BOLD$OS"
  ;;
esac

Shell() {
  usershell="$SHELL"
  if hascmd basename; then
    usershell="$(basename "$SHELL")"
  else
    err "Command '${UNDERLINE}basename$RESET${RED}' not found! Enjoy the full path."
  fi
  info "Shell" "$usershell"
  log "Shell : $usershell"
}

Terminal() {
  if ! [ "x$TERM" = "x" ]; then
    info "Terminal" "$TERM"

    log "Terminal : $TERM"
  fi
}

if hascmd uname; then
  Kernel() {
    info "Kernel" "$(uname -sr)"
    Arch="$(uname -p)"
    if [ "$Arch" = "unknown" ]; then
      info "Arch" "$(uname -m)"
      log "Arch : $(uname -m)"
    else
      info "Arch" "$Arch"
      log "Arch : $Arch"
    fi
  }
else
  case "$OS" in
  Linux)
    err "Command '${UNDERLINE}uname$RESET${RED}' not found! Using the good old /proc."
    Kernel() {
      IFS= read -r kernel </proc/version
      log "Kernel : $kernel"
      info "Kernel" "$kernel"
    }
    ;;
  Darwin)
    err "Command '${UNDERLINE}uname$RESET${RED}' not found! Using the good old sysctl."
    Kernel() {
      info "Kernel" "$(sysctl -n kern.version)"
    }
    ;;
  esac

fi

Packages() {
  :
}
if hascmd wc; then
  Packages() {
    pkg=0
    printf '%-10s : %s' "Packages" "$GREEN"

    if hascmd dpkg-query; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for dpkg-query..."
      printf 'dpkg (%s)' "$(dpkg-query -W | wc -l)"
    fi

    if hascmd pacman; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for pacman..."
      AURTotal=$(pacman -Qm | wc -l)
      PacmanTotal=$(pacman -Q | wc -l)
      printf 'pacman(Total : %s, System : %s, AUR : %s)' "$PacmanTotal" "$(($PacmanTotal - $AURTotal))" "$AURTotal"
    fi

    if hascmd dnf5; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for dnf5..."
      printf 'dnf5(%s)' "$(dnf5 list --installed | wc -l)"
    fi

    if hascmd dnf; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for dnf..."
      printf 'dnf(%s)' "$(dnf list --installed | wc -l)"
    fi

    # This check is super tuff as i wrote this on the iphone 8 plus
    if hascmd apk; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for apk..."
      printf 'apk(%s)' "$(apk list -I | wc -l)"
    fi

    if hascmd flatpak; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for flatpak..."
      flatpakapps=$(flatpak list --app | wc -l)
      flatpaktotal=$(flatpak list | wc -l)
      printf 'flatpak(Total : %s, Apps : %s, Runtime : %s)' "$flatpaktotal" "$flatpakapps" "$(($flatpaktotal - $flatpakapps))"
    fi

    if hascmd winget; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for winget..."
      printf 'winget(%s)' "$(($(winget list | wc -l) - 2))"
    fi

    if hascmd choco; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for chocolatey..."
      printf 'chocolatey(%s)' "$(($(choco list | wc -l) - 2))"
    fi

    if hascmd scoop; then
      if [ "$pkg" = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for scoop..."
      printf 'scoop(%s)' "$(($(scoop list | wc -l) - 5))"
    fi

    if hascmd brew; then
      if [ "$pkg" = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for homebrew..."
      printf 'homebrew(%s)' "$(brew list --formula | wc -l)"
    fi

    if hascmd snap; then
      if [ "$pkg" = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting snap..."
      printf 'snap(%s)' "$(($(snap list 2>/dev/null | wc -l) - 1))"
    fi

    # language-specific packages manager

    if hascmd pipx; then
      if [ "$pkg" = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for pipx..."
      printf 'pipx(%s)' "$(pipx list --short | wc -l)"
    fi

    if hascmd pip; then
      if [ "$pkg" = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      log "Waiting for pip..."
      printf 'pip('
      PipVenvPkg=0
      if ! [ "x$VIRTUAL_ENV" = "x" ]; then
        PipVenvPkg=$(pip list --format=freeze -l | wc -l)
        printf 'venv : %s, ' "$PipVenvPkg"
      fi
      PipPkg="$(($(pip list --format=freeze | wc -l) - $PipVenvPkg))"
      printf 'user : %s)' "$PipPkg"
    fi

    if [ $pkg = 0 ]; then
      err "No known ${UNDERLINE}packages manager$RESET${RED} found!"
      printf '%s' "$BOLD${RED}no"
    fi

    printf '%s\n' "$RESET"

    log "Packages manager checking done!"
  }
else
  err "Command '${UNDERLINE}wc$RESET${RED}' not found!"
fi

Language() {
  if [ "x$LANG" != "x" ]; then
    info "Language" "$LANG"
  fi
}

Colors() {
  printf '%s███%s' "$BLACK" "$RESET"
  printf '%s███%s' "$RED" "$RESET"
  printf '%s███%s' "$GREEN" "$RESET"
  printf '%s███%s' "$YELLOW" "$RESET"
  printf '%s███%s' "$BLUE" "$RESET"
  printf '%s███%s' "$MAGENTA" "$RESET"
  printf '%s███%s' "$CYAN" "$RESET"
  printf '%s███%s' "$WHITE" "$RESET"
  printf '\n'

  printf '%s███%s' "$BRIGHT_BLACK" "$RESET"
  printf '%s███%s' "$BRIGHT_RED" "$RESET"
  printf '%s███%s' "$BRIGHT_GREEN" "$RESET"
  printf '%s███%s' "$BRIGHT_YELLOW" "$RESET"
  printf '%s███%s' "$BRIGHT_BLUE" "$RESET"
  printf '%s███%s' "$BRIGHT_MAGENTA" "$RESET"
  printf '%s███%s' "$BRIGHT_CYAN" "$RESET"
  printf '%s███%s' "$BRIGHT_WHITE" "$RESET"
  printf '\n'
}

Break() {
  printf '\033[0m\n'
}

Line_Break() {
  printf '%s\n' '--------------------------'
}

TTY() {
  if hascmd tty; then
    if ! tty >/dev/null 2>&1; then
      err "${UNDERLINE}Not a TTY$RESET${RED}..Did you launch commands using ssh or \`cat | sh\` ?"
    else
      info "TTY" "$(tty)"
    fi
  else
    err "Command '${UNDERLINE}tty$RESET${RED}' not found!"
  fi
}

AkiyamaMizukiIsTuff() {
  printf '%s\n' "$UNDERLINE${transBLUE}Aki${transPINK}yama${transWHITE} Mizu${transPINK}ki${RESET} is${transBLUE} $UNDERLINE${BOLD}tuff$RESET"
}

Prin() {
  printf '%s\n' "$*"
}

Prin_no_endl() {
  printf '%s' "$*"
}

Editor(){
  if ! [ "x$EDITOR" = "x" ]; then
    if [ "$EDITOR" = "nvim" ]; then
      edit=neovim
    else
      edit="$EDITOR"
    fi
    info "Editor" "$edit"
  fi
}

Visual(){
  if ! [ "x$VISUAL" = "x" ]; then
    if [ "$VISUAL" = "nvim" ]; then
      vis=neovim
    else
      vis="$VISUAL"
    fi
    info "Visual" "$vis"
  fi
}

Pwd() {
  if [ "x$HOME" != "x" ] && [ "x$PWD" != "x" ]; then
    case "$PWD" in
      "$HOME")
        pwd='~'
        ;;
      "$HOME"/*)
        pwd="~/${PWD#"$HOME"/}"
        ;;
      *)
        pwd="$PWD"
        ;;
    esac
    info "PWD" "$pwd"
  fi
}

TimeDate(){
  if hascmd timedatectl; then
    TimeZone="$(timedatectl show -p Timezone --value)"
    Time="$(timedatectl show -p TimeUSec --value)"

    info "Timezone" "$TimeZone"
    info "Time" "$Time"
  fi
}

NightcordMembers(){
  set -- "Akiyama Mizuki" "Shinonome Ena" "Asahina Mafuyu" "Yoisaki Kanade"
  NightcordMember=$(( $(od -An -N4 -tu4 /dev/urandom) % $# + 1 ))

  case "$NightcordMember" in
    1) member="Akiyama Mizuki" ;;
    2) member="Shinonome Ena" ;;
    3) member="Asahina Mafuyu" ;;
    4) member="Yoisaki Kanade" ;;
  esac

  log "Got : $member"

  info "Random n25 member" "$member"

}

# Capitalized modules are user-facing modules
# Do NOT use uncapitalized modules in main

main() {
  Hostname
  Line_Break
  OS
  Init
  Shell
  Pwd
  Terminal
  TTY
  Break
  Kernel
  Memory
  CPU
  Uptime
  Packages
  TimeDate
  Break
  Music
  Desktop
  Editor
  Visual
  Break
  Colors
  # Break
  # AkiyamaMizukiIsTuff
  # Break
  # NightcordMembers
  # This module is just for fun.
}

fetch_info="$(main)"

print_fetch "$fetch_info"
