#!/bin/sh

transBLUE=$(printf '\033[38;2;91;206;250m')
transPINK=$(printf '\033[38;2;245;169;184m')
transWHITE=$(printf '\033[38;2;255;255;255m')

BLACK=$(printf '\033[30m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
MAGENTA=$(printf '\033[35m')
CYAN=$(printf '\033[36m')
WHITE=$(printf '\033[37m')

BRIGHT_BLACK=$(printf '\033[90m')
BRIGHT_RED=$(printf '\033[91m')
BRIGHT_GREEN=$(printf '\033[92m')
BRIGHT_YELLOW=$(printf '\033[93m')
BRIGHT_BLUE=$(printf '\033[94m')
BRIGHT_MAGENTA=$(printf '\033[95m')
BRIGHT_CYAN=$(printf '\033[96m')
BRIGHT_WHITE=$(printf '\033[97m')

RESET=$(printf '\033[0m')

err() {
  printf '%s\n' "$RED$*$RESET" >&2
}

color() {
  printf '%s%s%s\n' "$1" "$2" "$RESET"
}

info() {
  printf '%-10s : %s\n' "$1" "$GREEN$2$RESET"
}

logo=$(
  color "$transBLUE" '          _    _                               __  __ _           _    _ '
  color "$transPINK" '    /\   | |  (_)                             |  \/  (_)         | |  (_)'
  color "$transPINK" '   /  \  | | ___ _   _  __ _ _ __ ___   __ _  | \  / |_ _____   _| | ___ '
  color "$transWHITE" '  / /\ \ | |/ / | | | |/ _` | '\''_ ` _ \ / _` | | |\/| | |_  / | | | |/ / |'
  color "$transWHITE" ' / ____ \|   <| | |_| | (_| | | | | | | (_| | | |  | | |/ /| |_| |   <| |'
  color "$transPINK" '/_/    \_\_|\_\_|\__, |\__,_|_| |_| |_|\__,_| |_|  |_|_/___|\__,_|_|\_\_|'
  color "$transPINK" '                  __/ |                                                  '
  color "$transBLUE" '                 |___/                                                   '
)

if command >/dev/null 2>&1; then
  hascmd() {
    command -v "$1" >/dev/null 2>&1
  }
else
  err "Command 'command' not found! Falling back to 'type'."
  hascmd() {
    type "$1" >/dev/null 2>&1
  }
fi

# Use this when the entire shit is done
print_fetch() {
  info=$1

  exec 3<<EOF
$info
EOF

  while :; do
    logo_line=
    info_line=

    IFS= read -r logo_line <&0 || logo_done=1
    IFS= read -r info_line <&3 || info_done=1

    [ -n "$logo_line" ] || [ -n "$info_line" ] || break

    printf '%-73s %s\n' "$logo_line" "$info_line"

    unset logo_done info_done
  done <<EOF
$logo
EOF

  exec 3<&-
}

if hascmd uname; then
  OS=$(uname -s)
else
  OS=Linux
  err "Command 'uname' not found! Defaulting to Linux."
fi

Init() {
  :
}

Memory() {
  :
}

CPU() {
  :
}

Uptime() {
  :
}

Music() {
  :
}

LoadAVG() {
  :
}

OS() {
  :
}

if [ "$OS" = "Darwin" ]; then
  if ! hascmd sysctl; then
    err "Command 'sysctl' not found! Aborting fetch."
    exit 1
  fi
fi

case "$OS" in
Darwin)
  Hostname() {
    info "$USER@$(sysctl -n kern.hostname)"
  }

  Init() {
    info "Init" "launchd"

  }

  Desktop() {
    info "Desktop" "Springboard"
  }

  OS() {
    case "$(sysctl -n hw.product)" in
    iPhone*)
      DarwinOS=iOS
      ;;
    iPad*)
      DarwinOS=iPadOS
      ;;
    *)
      DarwinOS=macOS
      ;;
    esac
    info "OS" "$DarwinOS $(sysctl -n kern.osproductversion)"
  }

  Memory() {
    MemBytes="$(sysctl -n hw.memsize)"
    MemMiB=$((MemBytes / 1024 / 1024))
    info "Memory" "${MemMiB}MiB (Swap : $(sysctl -n vm.swapusage))"
  }

  CPU() {
    CPU="$(sysctl -n machdep.cpu.brand_string)"
    Cores="$(sysctl -n machdep.cpu.core_count)"
    info "CPU" "$CPU (${Cores} cores, $(sysctl -n hw.perflevel0.physicalcpu)P + $(sysctl -n hw.perflevel1.physicalcpu)E)"
  }

  if hascmd awk; then
    Uptime() {
      Boot="$(sysctl -n kern.boottime | awk -F'[ =,}]+' '{print $3}')"
      Now="$(date +%s)"
      Uptime=$((Now - Boot))

      info "Uptime" \
        "$((Uptime / 86400)) days, $(printf '%02d:%02d:%02d' \
          "$((Uptime / 3600 % 24))" \
          "$((Uptime / 60 % 60))" \
          "$((Uptime % 60))")"
    }

    LoadAVG() {
      Load="$(sysctl -n vm.loadavg | awk '{print $2, $3, $4}')"
      info "Load AVG" "$Load"
    }

  else
    err "What kind of apple produc is this that have to awk?"
  fi

  ;;

Linux | MINGW* | MSYS* | CYGWIN*)
  Hostname() {
    if hascmd hostname; then
      printf '%s\n' "$GREEN$USER@$(hostname)$RESET"
    else
      printf '%s\n' "$RED$USER$RESET@${RED}idk$RESET"
    fi
  }

  if [ "$OS" = "Linux" ]; then
    if hascmd readlink; then
      if hascmd basename; then
        if [ "$USER" = "root" ]; then
          Init() {
            init=$(readlink -f /proc/1/exe)
            info "Init" "$(basename "$init")"
          }
        fi
      else
        err "Command 'basename' not found!"
      fi
    else
      err "Command 'readlink' not found!"
    fi
  else
    Init() {
      info "Init" "wininit.exe"
    }
  fi

  if [ "$OS" = "Linux" ]; then
    if [ -f /etc/os-release ]; then
      OS() {
        . /etc/os-release
        info "OS" "$PRETTY_NAME"
      }
    else
      OS() {
        :
      }
      err "/etc/os-release not found! Bro have no identity like Mafuyu."
    fi
  else
    OS() {
      info "OS" "Windows"
    }
  fi

  if hascmd awk; then
    Memory() {
      MemTotal="$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo)"
      MemMiB=$((MemTotal / 1024))
      printf '%-10s : %s ' "Memory" "$GREEN${MemMiB}MiB"
      if [ -f /proc/swaps ]; then
        printf '%s' "$(awk 'NR > 1 { printf "%s%s : %sMiB", (NR > 2 ? ", " : "("), $1, $3/1024 } END { print ")" }' /proc/swaps)"
      fi
      printf '%s \n' "$RESET"
    }

    CPU() {
      CPU="$(awk -F: '/^model name/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' /proc/cpuinfo)"
      if [ "x$CPU" = "x" ]; then
        CPU=idk
        err 'No idea what the hell is the cpu.'
      fi
      info "CPU" "$CPU"
    }

    Uptime() {
      info "Uptime" "$(awk '{printf "%d days, %02d:%02d:%02d\n", $1/86400, $1/3600%24, $1/60%60, $1%60}' /proc/uptime)"
    }

  else
    err "WHAT THE FUCK THERE'S NO awk???"
  fi

  if [ "$OS" = "Linux" ]; then
    Desktop() {
      if [ "x$DESKTOP_SESSION" != "x" ]; then
        info "Desktop" "$DESKTOP_SESSION"
      else
        err "Are you running in the tty?"
      fi
    }
  else
    Desktop() {
      info "Desktop" "explorer.exe"
    }
  fi

  if [ "$OS" = "Linux" ]; then
    if hascmd playerctl; then
      Music() {
        title=$(playerctl metadata xesam:title)
        if [ "x$title" != "x" ]; then
          printf '%-10s : %s(%s)\n%s' \
            "Music" "$GREEN$title" "$(playerctl metadata xesam:artist)" "$RESET"
        fi
      }
    else
      err "Command 'playerctl' not found! No music information :( "
    fi
  fi

  LoadAVG() {
    if [ -f /proc/loadavg ]; then
      info "Load AVG" "$(cat /proc/loadavg)"
    else
      err "/proc/loadavg not found! Maybe there's no load."
    fi
  }
  ;;
*)
  err "idk what OS is $OS"
  ;;
esac

Shell() {
  usershell="$SHELL"
  if hascmd basename; then
    usershell="$(basename "$SHELL")"
  fi
  info "Shell" "$usershell"
}

Terminal() {
  info "Terminal" "$TERM"
}

if hascmd uname; then
  Kernel() {
    info "Kernel" "$(uname -sr)"
    Arch="$(uname -p)"
    if [ "$Arch" = "unknown" ]; then
      info "Arch" "$(uname -m)"
    else
      info "Arch" "$Arch"
    fi
  }
else
  case "$OS" in
  Linux)
    err "Comamnd 'uname' not found! Using the good old /proc."
    Kernel() {
      info "Kernel" "$(cat /proc/version)"
    }
    ;;
  Darwin)
    err "Comamnd 'uname' not found! Using the good old sysctl."
    Kernel() {
      info "Kernel" "$(sysctl -n kern.version)"
    }
    ;;
  esac

fi

Packages() {
  :
}
if hascmd wc; then
  Packages() {
    pkg=0
    printf '%-10s : %s' "Packages" "$GREEN"

    if hascmd dpkg-query; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'dpkg (%s)' "$(dpkg-query -W | wc -l)"
    fi

    if hascmd pacman; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'pacman(%s)' "$(pacman -Q | wc -l)"
    fi

    if hascmd dnf5; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'dnf5(%s)' "$(dnf5 list --installed | wc -l)"
    fi

    if hascmd dnf; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'dnf(%s)' "$(dnf list --installed | wc -l)"
    fi

    if hascmd flatpak; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'flatpak(%s)' "$(flatpak list | wc -l)"
    fi

    if hascmd winget; then
      if [ $pkg = 0 ]; then
        pkg=1
      else
        printf ', '
      fi
      printf 'winget(%s)' "$(($(winget list | wc -l) - 2))"
    fi

    if [ $pkg = 0 ]; then
      err "No known packages manager found!"
      printf '%s' "no"
    fi

    printf '%s\n' "$RESET"
  }
else
  err "Command 'wc' not found!"
fi

Language() {
  if [ "x$LANG" != "x" ]; then
    info "Language" "$LANG"
  fi
}

Colors() {
  printf '%s███%s' "$BLACK" "$RESET"
  printf '%s███%s' "$RED" "$RESET"
  printf '%s███%s' "$GREEN" "$RESET"
  printf '%s███%s' "$YELLOW" "$RESET"
  printf '%s███%s' "$BLUE" "$RESET"
  printf '%s███%s' "$MAGENTA" "$RESET"
  printf '%s███%s' "$CYAN" "$RESET"
  printf '%s███%s' "$WHITE" "$RESET"
  printf '\n'

  printf '%s███%s' "$BRIGHT_BLACK" "$RESET"
  printf '%s███%s' "$BRIGHT_RED" "$RESET"
  printf '%s███%s' "$BRIGHT_GREEN" "$RESET"
  printf '%s███%s' "$BRIGHT_YELLOW" "$RESET"
  printf '%s███%s' "$BRIGHT_BLUE" "$RESET"
  printf '%s███%s' "$BRIGHT_MAGENTA" "$RESET"
  printf '%s███%s' "$BRIGHT_CYAN" "$RESET"
  printf '%s███%s' "$BRIGHT_WHITE" "$RESET"
  printf '\n'
}

Break() {
  printf '\n'
}

Line_Break() {
  printf '%s\n' '--------------------------'
}

TTY() {
  if hascmd tty; then
    info "TTY" "$(tty)"
  else
    err "Command 'tty' not found!"
  fi
}

AkiyamaMizukiIsTuff() {
  printf '%s\n' "${transBLUE}Aki${transPINK}yama${transWHITE} Mizu${transPINK}ki is${transBLUE} tuff$RESET"
}

prin() {
  printf '%s\n' "$*"
}

main() {
  Hostname
  Line_Break
  OS
  Init
  Shell
  Terminal
  TTY
  Break
  Kernel
  Memory
  CPU
  Uptime
  Packages
  Music
  Break
  LoadAVG
  Colors
  # AkiyamaMizukiIsTuff
}

fetch_info=$(main)

print_fetch "$fetch_info"
